### ISSUE TITLE
[TASK]:  terminali resetlemeden ui değişikliklerini göremiyorum.

### ISSUE THREAD

**Issue by burak-senel** [Workintech-Graduate-Projects/nextgen-improvements#73]
### Sprint No

Sprint 10

### Gün No

Day 1

### Hata bulunan sayfanın URL'si

https://nextgen.workintech.com.tr/project/10/1/1

### Task No

10/1 gün projesi

### Karşılaştığınız hata nedir? Ne yapınca hata oluştu karşılaştınız?

1. örneğin ekranda initial state içerisinden aldığım bi veri var 0 ve bunu ekranda görüyorum.
2. "0" olan veriyi 5 yapıyorum ve kaydediyorum ekranda hiçbir şey değişmiyor.
3. Terminali durdurup tekrar başlatıyorum ve değişikliklerim geliyor. 
...

**Comment by gokhanozdemir** [comment]
@burak-senel reducer güncellledikçe, yandaki sayfayı refresh etmeliyiz. Reducer'ın ilk proje render'ında sadece 1 kez okunmasından kaynaklı, beklenen bir davranış.
